sudo: required
dist: dist
language: node_js
node_js:
  - "7"
cache: yarn
install:
  # - yarn global add bower
  - yarn
  # - bower install

script: 
  - ng build --prod

deploy:
  - provider: pages
    target_branch: master
    skip_cleanup: true
    github_token: $GITHUB_TOKEN 
    local_dir: dist
    on:
      branch: develop

  - provider: script
    script: sh ./deploy.sh
    skip_cleanup: true
    on:
      branch: develop